ecommerce/urls.py
from django.contrib import admin
from django.urls import path ,re_path
from django.conf import settings
from django.conf.urls.static import static

from products import views
from carts import views as cartviews
from orders import views as orderviews
from accounts import views as accountviews
from marketing import views as marketingviews
urlpatterns = [
    path('admin/', admin.site.urls),

    # urls of products app
    path('', views.home, name = 'home'),
    path('s/', views.search, name = 'search'),
    path('products/', views.products, name = 'products'),
    re_path(r'^products/(?P<slug>[\w-]+)/$' , views.single, name='single_product'),

    # urls of cart app
    re_path(r'^cart/(?P<id>\d+)/$' , cartviews.remove_from_cart, name='remove_from_cart'),
    re_path(r'^cart/(?P<slug>[\w-]+)/$' , cartviews.add_to_cart, name='add_to_cart'),
    re_path(r'^cart/$', cartviews.view, name = 'cart'),

    # urls of order app
    re_path(r'^checkout/$', orderviews.checkout, name = 'checkout'),
    re_path(r'^orders/$', orderviews.orders, name = 'user_order'),

    # urls of accounts app
    re_path(r'^accounts/logout/$', accountviews.logout_view, name = 'auth_logout'),
    re_path(r'^accounts/login/$', accountviews.login_view, name = 'auth_login'),
    re_path(r'^accounts/register/$', accountviews.registration_view, name = 'auth_register'),
    re_path(r'^accounts/activate/(?P<activation_key>\w+)$', accountviews.activation_view, name = 'activation_view'),
    re_path(r'^accounts/add_user_address$', accountviews.add_user_address, name = 'add_user_address'),
    re_path(r'^ajax/add_user_address/$', accountviews.add_user_address, name = 'ajax_add_user_address'),

    # urls of marketing app
    re_path(r'^ajax/dismiss_marketing_message/$', marketingviews.dismiss_marketing_message, name = 'dismiss_marketing_message'),
    re_path(r'^ajax/email_signup/$', marketingviews.email_signup, name = 'ajax_email_signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from accounts.models import UserAddress
from decimal import Decimal
from django.db import models
from django.conf import settings

# Create your models here.
from carts.models import Cart
from django.utils import timezone


STATUS_CHOICES=(
    ("Started","Started"),
    ("Abandoned","Abandoned"),
    ("Finished","Finished"),
)

try:
    tax_rate = settings.DEFAULT_TAX_RATE
except Exception as e:
    print(str(e))
    raise NotImplementedError(str(e))

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.CASCADE)
    order_id = models.CharField(max_length = 120, default = "ABC" , unique = True)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    status = models.CharField(max_length = 120, choices = STATUS_CHOICES, default = "Started")
    shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', on_delete=models.CASCADE, null=True,blank=True)
    billing_address = models.ForeignKey(UserAddress, related_name='billing_address', on_delete=models.CASCADE, null=True,blank=True)
    timestamp = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    sub_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places= 2)
    tax_total = models.DecimalField(default=0.00, max_digits=1000, decimal_places= 2)
    final_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places= 2)

    def __str__(self):
        return str(self.order_id)

    def get_final_amount(self):
        instance = Order.objects.get(id=self.id)
        two_dec_digits = Decimal(10) ** -2
        tax_rate_dec = Decimal("%s" %(tax_rate))
        sub_total_dec = Decimal(self.sub_total)
        tax_total_dec = Decimal(tax_rate_dec * sub_total_dec).quantize(two_dec_digits)
        instance.tax_total = tax_total_dec
        instance.final_total = sub_total_dec + tax_total_dec
        instance.save()
        return instance.final_total

    class Meta:
        ordering = ['-timestamp']

orders/views.py
from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from django.shortcuts import render, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from carts.models import Cart
from .models import Order
from .utils import id_generator
import time
import stripe
# Create your views here.

try:
    stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
    stripe_secret = settings.STRIPE_SECRET_KEY
except Exception as e:
    print(str(e))
    raise NotImplementedError(str(e))

stripe.api_key = stripe_secret

def orders(request):
    context = {}
    template = "orders/user.html"
    return render(request, template, context)

@login_required
def checkout(request):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))
    try:
        new_order = Order.objects.get(cart = cart)
    except Order.DoesNotExist:
        new_order = Order() 
        new_order.cart = cart
        new_order.user = request.user
        new_order.order_id = id_generator()
        new_order.save()
    except:
        new_order = None
        return HttpResponseRedirect(reverse("cart"))
    final_amount = 0
    if new_order is not None:
        new_order.sub_total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()
    try:
        address_added = request.GET.get("address_added")
    except:
        address_added = None
    if address_added is None:
        address_form = UserAddressForm()
    else:
        address_form = None
    current_addresses = UserAddress.objects.filter(user=request.user)
    billing_addresses = UserAddress.objects.get_billing_addresses(user=request.user)

    if request.method == 'POST':
        try:
            user_stripe = request.user.userstripe.stripe_id
            customer = stripe.Customer.retrieve(user_stripe)
        except:
            customer = None
            pass
        if customer is not None:
            billing_add = request.POST['billing_address']
            shipping_add = request.POST['shipping_address']
            token = request.POST['stripeToken']
            try:
                shipping_address_instance = UserAddress.objects.get(id=shipping_add)
            except:
                shipping_address_instance = None
            try:
                billing_address_instance = UserAddress.objects.get(id=billing_add)
            except:
                billing_address_instance = None
            card = stripe.Customer.create_source(
                customer.id,
                source="tok_visa",
            )
            card.address_line1 = billing_address_instance.address or None
            card.address_line2 = billing_address_instance.address2 or None
            card.address_city = billing_address_instance.city or None
            card.address_zip = billing_address_instance.zipcode or None
            card.address_state = billing_address_instance.state or None
            card.address_country = billing_address_instance.country or None
            print(card.address_country)
            print(card.address_line1)
            card.save()
            charge = stripe.Charge.create(
                amount=int(final_amount * 100),
                currency="inr",
                source="tok_visa",
                description="Charge for %s" %(request.user.username),
            )
        if charge['captured']:
            new_order.status = "Finished"
            new_order.shipping_address = shipping_address_instance
            new_order.billing_address = billing_address_instance
            new_order.save()
            del request.session['cart_id']
            del request.session['items_total']
            messages.success(request, "Your Cart Products has been purchased refer <a href='https://dashboard.stripe.com/test/payments'> https://dashboard.stripe.com/test/payments </a>",extra_tags='safe')
            return HttpResponseRedirect(reverse("user_order"))
    
    context = {
        "order": new_order,
        "address_form":address_form,
        "current_addresses": current_addresses,
        "billing_addresses": billing_addresses,
        "stripe_pub": stripe_pub,
        }
    template = "orders/checkout.html"
    return render(request, template, context)

templates/orders/checkout.html
{% extends 'base.html' %}

{% block head_title %}
MyChoices : Payment
{% endblock %}

<style>

  {% block styles %}
  .card-errors{
    color: red;
  }
  {% endblock %}
</style>

{% block content %}
<div class="row">
  <div class="col-sm-6">
      <br>
      <h3>
        Current Total: ₹ {{ order.get_final_amount }}
        <input class="form-check-input" type="hidden" id="disabledFieldsetCheck" disabled>
        <label class="form-check-label" for="disabledFieldsetCheck">
          <h6>
            (Tax Included)
          </h6> 
        </label>
      </h3>
        <form method="POST" id="payment-form">{% csrf_token %}
            {% if current_addresses %}
            <br>
                <h3>Shipping Addresses</h3>
                {% for address in current_addresses %}
                {% if request.user.userdefaultaddress.shipping.id == address.id %}
                <input value="{{ address.id }}" name="shipping_address" type="radio" class="form-check-input" checked="checked"> {{ address.get_address }} <br> 
                {% else %}
                <input value="{{ address.id }}" name="shipping_address" type="radio" class="form-check-input"> {{ address.get_address }} <br>
                {% endif %}
                {% endfor %}
                <br><a href="{% url 'add_user_address' %}" id="addShippingAddress" class="btn btn-primary">Add New Address</a><br>
            {% endif %}
            {% if billing_addresses %}
            <br>
            <h3>Billing Addresses</h3>
                {% for address in billing_addresses %}
                {% if request.user.userdefaultaddress.billing.id == address.id %}
                <input value="{{ address.id }}" name="billing_address" type="radio" class="form-check-input" checked="checked"> {{ address.get_address }} <br>
                {% else %}
                <input value="{{ address.id }}" name="billing_address" type="radio" class="form-check-input"> {{ address.get_address }} <br>
                {% endif %}      
                {% endfor %}
            {% endif %}
            {% if current_addresses is not None %}
            <br>
                <div class="form-row mb-3">
                  <label for="card-element" class="form-label">
                    <h3>
                        Credit Card Info:
                    </h3>
                  </label>
                  <div id="card-element" class="form-control">
                    <!-- A Stripe Element will be inserted here. -->
                  </div>
              
                  <!-- Used to display Element errors. -->
                  <div id="card-errors" role="alert"></div>
                </div>
                <button class="btn btn-outline-success form-control" type="submit">Submit Payment</button>
            {% endif %}
        </form>
    </div>
    <div class="col-sm-6" style="display: none;" id="shippingAddressForm">
        <br>
        <div class="card" style="border: none;">
            <div class="card-body">
                <h3>Add New Shipping Address:</h3>
                <form action="{% url 'ajax_add_user_address' %}?next=checkout" method="POST">{% csrf_token %}
                    {{ address_form.as_p }}
                    <input type="submit" value="Add New Shipping Address" class="form-control btn btn-outline-success mb-4">
                </form>
            </div>
        </div>
        <br>
    </div>
</div>

{% endblock %}


  <script>
  {% block jquery %}
  
  $("#addShippingAddress").click(function(e){
    e.preventDefault();
    $("#shippingAddressForm").fadeToggle();
  })

  {% if not current_addresses %}
  $("#shippingAddressForm").fadeToggle();
  {% endif %}

  var stripe = Stripe('{{stripe_pub}}');
  var elements = stripe.elements();
  
  // Custom styling can be passed to options when creating an Element.
  var style = {
    base: {
      // Add your base input styles here. For example:
      fontSize: '16px',
      color: '#32325d',
    },
  };
  
  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});
  
  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');
  
  // Create a token or display an error when the form is submitted.
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();
  
    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the customer that there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });
  
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
  
    // Submit the form
    form.submit();
  }
  
  {% endblock %}
  </script>

templates/orders/user.html
{% extends 'base.html' %}
{% block head_title %}
Orders
{% endblock %}
{% block content %}
{% for order in user.order_set.all %}
<h5>
    Your Order at {{order.updated}} of total of {{order.final_total}} has been charged. <br>
    Enjoy Your Purchase. <br><br>
</h5>
{% endfor %}
{% endblock %}